### ISSUE TITLE
Steam Cache install error

### ISSUE THREAD

**Issue by Termitebug** [HBDK/Rockons#1]
I get following error when copying .json's to rockstor-metastore folder: 

`   (Error while processing Rock-on profile at (/opt/rockstor/rockons-metastore/steamcache-dns.json).). Lower level exception: (No JSON object could be decoded).. 
  Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 453, in _get_available
    ds = json.load(fo)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`
I'm running Rockstor 3.9.2.-57. Any suggestions of what needed to be edited in the .json file?

**Comment by Termitebug** [comment]
It seems that Steam .json's are outdated. Sniproxy and monolith are the successors
